# Generated by Django 5.2.7 on 2026-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dailyattendance_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='punch_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='punch_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
