# Generated by Django 5.2.7 on 2026-08-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dailyattendance_punch_in_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='punch_in_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
