# Generated by Django 5.2.7 on 2026-09-28 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dailyattendance_punch_in_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_punch_in', models.TimeField(blank=True, null=True)),
                ('old_punch_out', models.TimeField(blank=True, null=True)),
                ('new_punch_in', models.TimeField(blank=True, null=True)),
                ('new_punch_out', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Mandatory reason for audit trail.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('requested_punch_in', models.TimeField(blank=True, null=True)),
                ('requested_punch_out', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Explanation for missing punch or correction.')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeFaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_descriptor', models.JSONField(blank=True, help_text='128-dimensional biometric descriptor embedding array.', null=True)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('anti_spoofing_passed', models.BooleanField(default=False)),
                ('liveness_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Paid Leave', 'Paid Leave'), ('Half Day', 'Half Day')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_days', models.IntegerField(default=1)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('designation', models.CharField(blank=True, default='Employee', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('joining_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('face_auth_exempt', models.BooleanField(default=False, help_text='Exempt from face scanner if camera hardware fails or medical exemption granted.')),
                ('exemption_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='face_verified_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='face_verified_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='late_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='punch_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='punch_out_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='punch_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='verification_method',
            field=models.CharField(choices=[('face_biometric', 'Face Biometric Verification'), ('manual_admin', 'Admin Manual Correction'), ('exempt_override', 'Exempt Override')], default='face_biometric', max_length=50),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='working_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['user', 'date'], name='app_dailyat_user_id_9def73_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyattendance',
            index=models.Index(fields=['date'], name='app_dailyat_date_4bc17e_idx'),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='app.dailyattendance'),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeefaceprofile',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeefaceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
