from datetime import time, datetime, timedelta
import math
import secrets
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    employee_id = models.CharField(max_length=50, unique=True, null=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True, related_name='employees')
    designation = models.CharField(max_length=100, blank=True, default='Employee')
    phone = models.CharField(max_length=20, blank=True, default='')
    profile_picture = models.ImageField(upload_to='profiles/', null=True, blank=True)
    joining_date = models.DateField(default=timezone.now, null=True, blank=True)
    face_auth_exempt = models.BooleanField(
        default=False,
        help_text="Exempt from face scanner if camera hardware fails or medical exemption granted."
    )
    exemption_reason = models.CharField(max_length=255, blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} Profile ({self.employee_id or 'No ID'})"

    @property
    def full_name(self):
        name = f"{self.user.first_name} {self.user.last_name}".strip()
        return name if name else self.user.username


class EmployeeFaceProfile(models.Model):
    ENROLLMENT_STATUS_CHOICES = [
        ('NOT_REGISTERED', 'Not Registered'),
        ('PENDING', 'Registration Pending'),
        ('REGISTERED', 'Registered'),
        ('RE_ENROLLMENT_REQUIRED', 'Re-enrollment Required'),
    ]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='face_profile')
    # 128-dimensional floating point descriptor array generated by FaceRecognitionNet
    face_descriptor = models.JSONField(
        null=True,
        blank=True,
        help_text="128-dimensional biometric descriptor embedding array."
    )
    enrollment_status = models.CharField(
        max_length=30,
        choices=ENROLLMENT_STATUS_CHOICES,
        default='NOT_REGISTERED'
    )
    is_enrolled = models.BooleanField(default=False)
    sample_count = models.IntegerField(default=0)
    enrolled_at = models.DateTimeField(null=True, blank=True)
    enrolled_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='enrolled_employees'
    )
    anti_spoofing_passed = models.BooleanField(default=False)
    liveness_score = models.FloatField(default=0.0)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} - Face Profile ({self.get_enrollment_status_display()})"

    def save(self, *args, **kwargs):
        # Keep is_enrolled synced with enrollment_status
        if self.enrollment_status == 'REGISTERED' and self.face_descriptor:
            self.is_enrolled = True
        else:
            self.is_enrolled = False
        super().save(*args, **kwargs)

    def verify_descriptor(self, candidate_descriptor, threshold=0.55):
        """
        Calculates the Euclidean distance between candidate_descriptor and stored face_descriptor.
        Face Recognition Net uses 0.5 - 0.6 as standard Euclidean distance threshold.
        Distance <= threshold means genuine match.
        """
        if self.enrollment_status != 'REGISTERED' or not self.face_descriptor or not candidate_descriptor:
            return False, 999.0

        if len(self.face_descriptor) != len(candidate_descriptor):
            return False, 999.0

        try:
            dist = math.dist(self.face_descriptor, candidate_descriptor)
            return (dist <= threshold), dist
        except Exception:
            sq_sum = sum((a - b) ** 2 for a, b in zip(self.face_descriptor, candidate_descriptor))
            dist = math.sqrt(sq_sum)
            return (dist <= threshold), dist


class FaceChallenge(models.Model):
    """
    Cryptographic single-use nonce to prevent replay attacks and token reuse.
    A challenge token is issued to the client camera session and must be consumed within 120s.
    """
    challenge_id = models.CharField(max_length=64, unique=True, db_index=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='face_challenges')
    action = models.CharField(max_length=30, default='punch')
    created_at = models.DateTimeField(default=timezone.now)
    is_consumed = models.BooleanField(default=False)
    consumed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def is_valid(self):
        if self.is_consumed:
            return False
        age = (timezone.now() - self.created_at).total_seconds()
        return age <= 120.0

    @classmethod
    def create_challenge(cls, user, action='punch'):
        token = secrets.token_urlsafe(32)
        return cls.objects.create(challenge_id=token, user=user, action=action)


class FaceVerificationLog(models.Model):
    """
    Audit log of all face recognition verification attempts (successes and rejections).
    Does NOT store raw biometric descriptors or footage, ensuring GDPR/privacy compliance.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='face_logs')
    timestamp = models.DateTimeField(default=timezone.now)
    action = models.CharField(max_length=40)  # 'Punch In', 'Punch Out', 'Enrollment'
    status = models.CharField(max_length=40)  # 'Verified', 'Mismatch', 'Multiple Faces', 'No Face', 'Replay Blocked', 'Not Enrolled'
    confidence_distance = models.FloatField(null=True, blank=True)
    ip_address = models.CharField(max_length=45, blank=True, default='')
    user_agent = models.CharField(max_length=255, blank=True, default='')
    message = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"[{self.timestamp.strftime('%Y-%m-%d %H:%M:%S')}] {self.user.username} - {self.action}: {self.status}"


class Holiday(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField(unique=True)
    description = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f"{self.name} ({self.date})"


class DailyAttendance(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='attendances')
    date = models.DateField(default=timezone.now)

    punch_in = models.TimeField(null=True, blank=True)
    punch_out = models.TimeField(null=True, blank=True)

    punch_in_latitude = models.DecimalField(
        max_digits=10,
        decimal_places=7,
        null=True,
        blank=True
    )

    punch_in_longitude = models.DecimalField(
        max_digits=10,
        decimal_places=7,
        null=True,
        blank=True
    )

    punch_in_location = models.CharField(
        max_length=255,
        null=True,
        blank=True
    )

    punch_out_latitude = models.DecimalField(
        max_digits=10,
        decimal_places=7,
        null=True,
        blank=True
    )

    punch_out_longitude = models.DecimalField(
        max_digits=10,
        decimal_places=7,
        null=True,
        blank=True
    )

    punch_out_location = models.CharField(
        max_length=255,
        null=True,
        blank=True
    )

    verification_method = models.CharField(
        max_length=50,
        default='face_biometric',
        choices=[
            ('face_biometric', 'Face Biometric Verification'),
            ('manual_admin', 'Admin Manual Correction'),
            ('exempt_override', 'Exempt Override'),
        ]
    )
    face_verified_in = models.BooleanField(default=False)
    face_verified_out = models.BooleanField(default=False)
    confidence_score = models.FloatField(null=True, blank=True)

    is_late = models.BooleanField(default=False)
    late_minutes = models.IntegerField(default=0)
    working_hours = models.FloatField(default=0.0)
    notes = models.TextField(blank=True, default='')

    class Meta:
        unique_together = ('user', 'date')
        ordering = ['-date']
        indexes = [
            models.Index(fields=['user', 'date']),
            models.Index(fields=['date']),
        ]

    def __str__(self):
        return f"{self.user.username} - {self.date}"

    def update_calculations(self):
        """
        Recalculates working hours, late minutes, and late status.
        Office Start: 9:30 AM
        On-time: 9:30 AM to 9:35 AM (inclusive)
        Late: after 9:35 AM
        """
        if self.punch_in:
            cutoff = time(9, 35, 0)
            target = time(9, 30, 0)
            if self.punch_in > cutoff:
                self.is_late = True
                in_mins = self.punch_in.hour * 60 + self.punch_in.minute + (self.punch_in.second / 60.0)
                target_mins = target.hour * 60 + target.minute
                self.late_minutes = max(0, int(round(in_mins - target_mins)))
            else:
                self.is_late = False
                self.late_minutes = 0
        else:
            self.is_late = False
            self.late_minutes = 0

        if self.punch_in and self.punch_out:
            in_sec = self.punch_in.hour * 3600 + self.punch_in.minute * 60 + self.punch_in.second
            out_sec = self.punch_out.hour * 3600 + self.punch_out.minute * 60 + self.punch_out.second
            diff_sec = max(0, out_sec - in_sec)
            self.working_hours = round(diff_sec / 3600.0, 2)
        else:
            self.working_hours = 0.0

    def save(self, *args, **kwargs):
        self.update_calculations()
        super().save(*args, **kwargs)

    @property
    def status(self):
        """
        Returns accurate business status:
        - Holiday: if holiday or Sunday
        - Present / On Time: punch in <= 9:35 AM with punch out
        - Late: punch in > 9:35 AM with punch out
        - Punch Out Pending: punch in recorded, punch out missing
        - Absent: no punch in and day closed
        """
        if self.date.weekday() == 6:
            return "Holiday"

        if self.punch_in:
            if not self.punch_out:
                return "Punch Out Pending"
            if self.punch_in <= time(9, 35, 0):
                return "Present / On Time"
            else:
                return "Late"

        now_dt = timezone.localtime(timezone.now())
        today = now_dt.date()
        closing_time = time(18, 30, 0)

        if self.date < today:
            return "Absent"
        elif self.date == today:
            if now_dt.time() >= closing_time:
                return "Absent"
            return "Not Marked"
        else:
            return "Scheduled"

    @property
    def status_badge_class(self):
        s = self.status
        if "Present" in s:
            return "badge-present"
        elif "Late" in s:
            return "badge-late"
        elif "Pending" in s:
            return "badge-pending"
        elif "Holiday" in s:
            return "badge-holiday"
        elif "Absent" in s:
            return "badge-absent"
        return "badge-secondary"

    @property
    def row_css_class(self):
        s = self.status
        if "Present" in s:
            return "row-present"
        elif "Late" in s:
            return "row-late"
        elif "Pending" in s:
            return "row-pending"
        elif "Holiday" in s:
            return "row-holiday"
        elif "Absent" in s:
            return "row-absent"
        return ""

    @property
    def formatted_working_hours(self):
        if not self.punch_in or not self.punch_out:
            return "-"
        in_sec = self.punch_in.hour * 3600 + self.punch_in.minute * 60 + self.punch_in.second
        out_sec = self.punch_out.hour * 3600 + self.punch_out.minute * 60 + self.punch_out.second
        diff_sec = max(0, out_sec - in_sec)
        hours = diff_sec // 3600
        mins = (diff_sec % 3600) // 60
        return f"{hours} hrs {mins} mins"

    @property
    def delay_display(self):
        if self.is_late and self.late_minutes > 0:
            return f"{self.late_minutes} min late"
        elif self.punch_in:
            return "On Time"
        return "-"


class LeaveRequest(models.Model):
    LEAVE_CHOICES = [
        ('Casual Leave', 'Casual Leave'),
        ('Sick Leave', 'Sick Leave'),
        ('Paid Leave', 'Paid Leave'),
        ('Unpaid Leave', 'Unpaid Leave'),
        ('Other', 'Other'),
    ]

    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
        ('Cancelled', 'Cancelled'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='leave_requests')
    leave_type = models.CharField(max_length=50, choices=LEAVE_CHOICES)
    from_date = models.DateField()
    to_date = models.DateField()
    total_days = models.IntegerField(default=1)
    reason = models.TextField()
    supporting_document = models.FileField(upload_to='leave_docs/', null=True, blank=True)
    status = models.CharField(max_length=20, default='Pending', choices=STATUS_CHOICES)
    is_cancelled = models.BooleanField(default=False)
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='reviewed_leaves'
    )
    reviewed_at = models.DateTimeField(null=True, blank=True)
    admin_remark = models.CharField(max_length=255, blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.username} - {self.leave_type} ({self.from_date} to {self.to_date})"


class AttendanceCorrectionRequest(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='correction_requests')
    date = models.DateField()
    requested_punch_in = models.TimeField(null=True, blank=True)
    requested_punch_out = models.TimeField(null=True, blank=True)
    reason = models.TextField(help_text="Explanation for missing punch or correction.")
    status = models.CharField(max_length=20, default='Pending', choices=STATUS_CHOICES)
    admin_notes = models.TextField(blank=True, default='')
    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='reviewed_corrections'
    )
    reviewed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Correction: {self.user.username} for {self.date} ({self.status})"


class AttendanceAuditLog(models.Model):
    attendance = models.ForeignKey(DailyAttendance, on_delete=models.CASCADE, related_name='audit_logs')
    modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    old_punch_in = models.TimeField(null=True, blank=True)
    old_punch_out = models.TimeField(null=True, blank=True)
    new_punch_in = models.TimeField(null=True, blank=True)
    new_punch_out = models.TimeField(null=True, blank=True)
    reason = models.TextField(help_text="Mandatory reason for audit trail.")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Audit: {self.attendance.user.username} on {self.attendance.date} by {self.modified_by.username}"


# Signal to create UserProfile and EmployeeFaceProfile automatically
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profiles(sender, instance, created, **kwargs):
    UserProfile.objects.get_or_create(user=instance)
    face_prof, _ = EmployeeFaceProfile.objects.get_or_create(user=instance)
    if face_prof.is_enrolled and face_prof.enrollment_status != 'REGISTERED':
        face_prof.enrollment_status = 'REGISTERED'
        face_prof.save(update_fields=['enrollment_status'])